### ISSUE TITLE
To implement `Into<std::process::Output>` for `process_control::Output`

### ISSUE THREAD

**Issue by Binlogo** [dylni/process_control#28]
Implement `Into<std::process::Output>` for `process_control::Output` to facilitate interaction with std's Output.

While we can convert `std::process::Output` to `process_control::Output`, the reverse conversion is not currently supported. (If I'm overlooking something, please correct me.)

**Comment by dylni** [comment]
I do want to do this, but it may be challenging. There are two issues:
- On Unix, `process::ExitStatus` stores a single code and uses `libc` functions to interpret it. However, since this crate calls different APIs, it instead has the interpreted value and the value kind (see below). APIs to convert back to a single code are much less generally available than those to convert in the opposite direction, but I will see if I can get a "best-effort" API in place here.
- Also because of calling those different APIs, `process::ExitStatus` is forced to truncate the error code, so this crate would need to do the same. This is not an issue if the conversion is instead provided as a dedicated method that truncates, but `Into` could not be used.

https://github.com/dylni/process_control/blob/763e5d232cd36c2780dd16b74b788dd0dfb5c15a/src/unix/exit_status.rs#L57-L60

**Comment by dylni** [comment]
I was able to implement this in a much better way than described above. Published in 4.2.0 ([`Output::into_std_lossy`](https://docs.rs/process_control/4.2.0/process_control/struct.Output.html#method.into_std_lossy)).
